#!/usr/bin/env bash

Install and setup HAproxy
apt-get update
apt-get -y install haproxy

#Set the hostnames of the web servers
echo "127.0.0.1 53432-web-01" >> /etc/hosts
echo "127.0.0.1 53432-web-02" >> /etc/hosts

#Restart networking to apply hostname changes
systemctl restart networking

#Configure HAproxy
sed -i 's/ENABLED=.*/ENABLED=1/' /etc/default/haproxy

echo "
frontend web
bind *:80
mode http
default_backend webservers
backend webservers
mode http
balance roundrobin
option httpclose
option forwardfor
server 53432-web-01 53432-web-01:80 check
server 53432-web-02 53432-web-02:80 check
" >> /etc/haproxy/haproxy.cfg

#Restart HAproxy
systemctl restart haproxy

#Enable HAproxy init script
systemctl enable haproxy
