#!/usr/bin/env bash
# This script installs and configures HAproxy on a new Ubuntu machine

# Get the STUDENT_ID from the user
read -p "Enter your STUDENT_ID: " STUDENT_ID

# Set the hostnames of the web servers
echo "127.0.0.1 53432-web-01" >> /etc/hosts
echo "127.0.0.1 53432-web-02" >> /etc/hosts

# Install HAproxy
apt-get update
apt-get -y install haproxy

# Configure HAproxy
cat > /etc/haproxy/haproxy.cfg <<EOF
frontend web
    bind *:80
    mode http
    default_backend webservers

backend webservers
    mode http
    balance roundrobin
    option httpclose
    option forwardfor
    server web-01 53432-web-01:80 check
    server web-02 53432-web-02:80 check
EOF

# Enable HAproxy init script
systemctl enable haproxy

# Restart HAproxy
systemctl restart haproxy
