#!/usr/bin/env bash
# Installs and setup haproxy

apt-get update
apt-get -y install haproxy

sed -i 's/ENABLED=.*/ENABLED=1/' /etc/default/haproxy

echo "
frontend web
        bind *:80
        mode http
        default_backend webservers
backend webservers
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 53432-web-01 53432-web-01:80 check
        server 53432-web-02 53432-web-02:80 check
" >> /etc/haproxy/haproxy.cfg

systemctl restart haproxy
